[package]
name = "bft"
version = "0.1.0"
edition = "2021"

[dependencies]
bft_interp = { path = "bft_interp" }
bft_types = { path = "bft_types" }
clap = { version = "4.4.6", features = ["derive"] }
clap-num = "1.0.2"

[workspace]
members = [
  "bft_interp",
  "bft_types"
]
